### ISSUE TITLE
Updating ohibc website

### ISSUE THREAD

**Issue by Melsteroni** [ohibc/issues#2]
(This has been copied into the github.com/ohi-science)
1. Go to: https://github.com/ohibc/ohibc.github.io
2. Select settings:
   ![image](https://cloud.githubusercontent.com/assets/5685517/5769317/972b7e72-9cce-11e4-9b76-8ace3d9d200c.png)
3. Select "Automatic page generator":
   ![image](https://cloud.githubusercontent.com/assets/5685517/5769324/b243c548-9cce-11e4-89df-a0056becdc20.png)
4. Make edits directly in this window using Markdown language:
   ![image](https://cloud.githubusercontent.com/assets/5685517/5769333/ca733c5c-9cce-11e4-9b8c-2b03d3a1d492.png)
5.  If you need to add/change a figure, add it to the "images" folder:
   ![image](https://cloud.githubusercontent.com/assets/5685517/5769352/f4fdfa16-9cce-11e4-9a66-d01c389dfbff.png)
   And, then, navigate to the image, right click on it, and select "Copy image URL":
   ![image](https://cloud.githubusercontent.com/assets/5685517/5769362/1b06df2a-9ccf-11e4-9414-98d13bfea647.png)
6. After the edits are made: Click on "Continue to layouts".
   ![image](https://cloud.githubusercontent.com/assets/5685517/5823489/046d3018-a092-11e4-9675-d9ed56e3b6a0.png)
7. Select a layout.  I used the "Dinky" layout.  But feel free to explore other layouts in case something looks better to you (this will not mess anything up).  
   ![image](https://cloud.githubusercontent.com/assets/5685517/5823504/373cbf36-a092-11e4-887b-ab5a03997c8d.png)
8. Select "Publish page".
9. Then go look at your work at: http://ohibc.github.io

This is super duper easy!!!

**Comment by jules32** [comment]
Awesome Mel! Thanks so much!

**Comment by Melsteroni** [comment]
I put this in the "issues" for ohibc because really, it only seems to
relate to this project. Should we keep the "issues" repository for topics
that are only going to relate to ohibc? (but avoid putting tasks or issues
that relate to OHI in general?)

I can also move to OHI-Science

**Comment by jules32** [comment]
Yes, there are pros and cons to keeping BC things separately here: pro
because it's more contained, but con because we have to remember where we
put things.

Maybe we can use ohibc issues for OHIBC planning and the literature
summaries/discussions we talked about, and keep our tasks in ohi-science
issues?

On Thu, Jan 15, 2015 at 4:11 PM, Melsteroni notifications@github.com
wrote:

> I put this in the "issues" for ohibc because really, it only seems to
> relate to this project. Should we keep the "issues" repository for topics
> that are only going to relate to ohibc? (but avoid putting tasks or issues
> that relate to OHI in general?)
> 
> I can also move to OHI-Science
> 
> On Thu, Jan 15, 2015 at 4:08 PM, Julia Lowndes notifications@github.com
> wrote:
> 
> > Awesome Mel! Thanks so much!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ohibc/issues/issues/2#issuecomment-70187241.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ohibc/issues/issues/2#issuecomment-70187585.

## 

Julia Stewart Lowndes, PhD
Project Scientist, Ocean Health Index http://www.oceanhealthindex.org
National Center for Ecological Analysis and Synthesis (NCEAS
http://www.nceas.ucsb.edu)
University of California, Santa Barbara
735 State Street, Suite 300
Santa Barbara, CA, 93101, USA
Phone: 1-805-893-7523

**Comment by bshalpern** [comment]
because for now there will be a lot of overlap (synergy) between needs 
and activities, it does seem to make sense to keep things in one place.  
But having a flag that notes things are OHIBC seems very useful.

On 1/15/2015 4:49 PM, Julia Lowndes wrote:

> Yes, there are pros and cons to keeping BC things separately here: pro
> because it's more contained, but con because we have to remember where we
> put things.
> 
> Maybe we can use ohibc issues for OHIBC planning and the literature
> summaries/discussions we talked about, and keep our tasks in ohi-science
> issues?
> 
> On Thu, Jan 15, 2015 at 4:11 PM, Melsteroni notifications@github.com
> wrote:
> 
> > I put this in the "issues" for ohibc because really, it only seems to
> > relate to this project. Should we keep the "issues" repository for 
> > topics
> > that are only going to relate to ohibc? (but avoid putting tasks or 
> > issues
> > that relate to OHI in general?)
> > 
> > I can also move to OHI-Science
> > 
> > On Thu, Jan 15, 2015 at 4:08 PM, Julia Lowndes 
> > notifications@github.com
> > wrote:
> > 
> > > Awesome Mel! Thanks so much!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/ohibc/issues/issues/2#issuecomment-70187241.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ohibc/issues/issues/2#issuecomment-70187585.
> 
> ## 
> 
> Julia Stewart Lowndes, PhD
> Project Scientist, Ocean Health Index http://www.oceanhealthindex.org
> National Center for Ecological Analysis and Synthesis (NCEAS
> http://www.nceas.ucsb.edu)
> University of California, Santa Barbara
> 735 State Street, Suite 300
> Santa Barbara, CA, 93101, USA
> Phone: 1-805-893-7523
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ohibc/issues/issues/2#issuecomment-70191098.

## 

---

Benjamin S. Halpern
Professor, Bren School of Environmental Science and Management
UCSB, Santa Barbara, CA 93106
(ph) 805.893.2862
halpern@bren.ucsb.edu

Chair in Marine Conservation, Imperial College London
Grand Challenges in Ecosystems and the Environment
http://www3.imperial.ac.uk/ecosystemsandenvironment

Director, Center for Marine Assessment and Planning (CMAP)
http://cmap.msi.ucsb.edu

Senior Fellow, UN Envir. Prog.- World Conserv. Monitor. Cent. (UNEP-WCMC)

Research Biologist, Nat'l. Center for Ecol. Anal. & Synth. (NCEAS)
735 State St., Suite 300, Santa Barbara, CA 93101
phone: 805.893.7470 (new as of June 25); fax: 805.892.2510

---
